kind: Service
metadata:
  name: nginx-oidc-gw-sync-zones
  namespace: "{{ extra_volterra_namespace }}"
  labels:
    owner: "{{ extra_owner_email.split('@')[0] }}"
    project: "cloudbuilder"
  annotations:
    ves.io/app: nginx-secure-access
    ves.io/virtual-sites: shared/shared-services-secure-access
    ves.io/workload-flavor: nginx-secure-access
spec:
  selector:
    ves.io/workload: nginx-secure-access
  clusterIP: None
  type: ClusterIP
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  internalTrafficPolicy: Cluster
